name: Deploy OIDC provider
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-hydra:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          bash deploy.sh